### ISSUE TITLE
nia_stats_and_summaries.calculate_auc(): present network-specific measures separately

### ISSUE THREAD

**Issue by joshbear** [neurosutton/connectivity#10]
It looks like a DF that has values for multiple subnetworks (such as nx_num_of_comm) will calculate the AUC based on the values across all networks if a network is not specified. It should probably either (1) require a network to be specified, or (2) calculate the AUCs and permutations separately for each subnetwork.

**Comment by neurosutton** [comment]
I think this is related to whole brain not being specified as a string. I'm pretty sure that there just has to be a check for np.nan, rather than 'nan' as it has been represented previously. Checking it out, but I think that is the issue/fix.

**Comment by neurosutton** [comment]
#13, #12, and this one were all related to (1) the 'nan' string issue and/or (2) a subtle change adding a recorded threshold to subgraph analysis that must have been committed after you started processing the graphs. I'll close all three issues. Please reopen, if you are still having trouble.
