### ISSUE TITLE
nia_stats_and_summaries.calculate_auc(): specifying an individual network does not work

### ISSUE THREAD

**Issue by joshbear** [neurosutton/connectivity#12]
Specifying an individual network raises an error that seems to be related to the group definitions or the data pulled for the groups.

CALL: 
nss.calculate_auc(df, network='default')  # output for this call is shown below
nss.calculate_auc(df, network='default', msrs=['sg_num_connected_comp'])  # same error, not shown 

OUTPUT: 

Working through ['gm_local_efficiency', 'gm_shortest_path', 'mean_degree', 'modularity', 'nx_num_of_comm', 'sg_average_clustering', 'sg_global_efficiency', 'sg_largest_component', 'sg_num_connected_comp', 'sg_num_total_edges', 'sg_shortest_path_length'] for FCN: default
GM_LOCAL_EFFICIENCY
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-11-7283454be858> in <module>
----> 1 nss.calculate_auc(df, network='default')

~/research/eses_connectivity/scripts/neurosutton/connectivity/nia_stats_and_summaries.py in calculate_auc(df, network, grouping_col, name_id_col, bootstrap, msrs, subgroups)
     76         group1_members = set(
     77             tmp.loc[tmp[grouping_col] == groups[0], name_id_col]) # List of subject IDs
---> 78         study_exp_auc_diff = auc_group_diff(
     79             tmp, group1_members, msr, group_match_col=name_id_col)
     80         print(f'{groups[0]} - {groups[1]} = {study_exp_auc_diff}')

~/research/eses_connectivity/scripts/neurosutton/connectivity/nia_stats_and_summaries.py in auc_group_diff(df, group1_list, msr, group_match_col)
    115     thrs = sorted(set(df['threshold'].dropna()))
    116 
--> 117     group1_auc = metrics.auc(thrs, group1_means)
    118     group2_auc = metrics.auc(thrs, group2_means)
    119     return group1_auc - group2_auc

~/bin/anaconda3/envs/mnedev/lib/python3.8/site-packages/sklearn/metrics/_ranking.py in auc(x, y)
     82 
     83     if x.shape[0] < 2:
---> 84         raise ValueError('At least 2 points are needed to compute'
     85                          ' area under curve, but x.shape = %s' % x.shape)
     86 

ValueError: At least 2 points are needed to compute area under curve, but x.shape = 0

**Comment by neurosutton** [comment]
#10, #13, and this one were all related to (1) the 'nan' string issue and/or (2) a subtle change adding a recorded threshold to subgraph analysis that must have been committed after you started processing the graphs. I'll close all three issues. Please reopen, if you are still having trouble.
