### ISSUE TITLE
nia_stats_and_summaries.calculate_auc(): specifying subnetwork measure does not work 

### ISSUE THREAD

**Issue by joshbear** [neurosutton/connectivity#13]
The code will run when you call calculate_auc() with a df and a subgroup measure, but the output is nonsensical. This could be related to the other issue raised about separately analyzing each subnetwork. 

CODE: 
nss.calculate_auc(df, msrs=['sg_num_connected_comp'])

OUTPUT:
       1%|          | 28/4999 [00:00<00:17, 276.81it/s]
Working through ['sg_num_connected_comp'] for FCN: None
SG_NUM_CONNECTED_COMP
eses - hc = nan
     100%|██████████| 4999/4999 [00:16<00:00, 310.68it/s]
The experimental AUC difference, nan, occurs 0.0% of the time in the boostrapped results.
<img width="382" alt="image" src="https://user-images.githubusercontent.com/3783550/107974907-826cf400-6f74-11eb-8649-a39dd8e0b8d9.png">

**Comment by neurosutton** [comment]
I think #10 , #12 , and this one are all related. The FCN "none", which is whole brain, does not have subgraph metrics associated with it. I will put in a check to make sure that comparisons are not made for metrics that do not exist.

**Comment by neurosutton** [comment]
#10, #12, and this one were all related to (1) the 'nan' string issue and/or (2) a subtle change adding a recorded threshold to subgraph analysis that must have been committed after you started processing the graphs. I'll close all three issues. Please reopen, if you are still having trouble.
