### ISSUE TITLE
incorrect means/SDs (possibly p-values) in nss.summarize_group_differences

### ISSUE THREAD

**Issue by joshbear** [neurosutton/connectivity#15]
Noticed some strange behavior in summarize_group_differences(). The means and stds are all the same for the following query, and the p-values are clearly coming from somewhere else. Additionally, the p-values might be correct, but I suspect they are not as the group curves would suggest that 0.6 should be significant and 0.9 should not be. 
<img width="993" alt="image" src="https://user-images.githubusercontent.com/3783550/108427951-1fd95980-71fb-11eb-8a94-ec1aaa0d2435.png">

**Comment by neurosutton** [comment]
The logic in line 107, where it groups by a specific column is incorrect. The indices for the pvalues are specific correctly above that, so I think they are okay.
