### ISSUE TITLE
plot_score_by_network() returning error

### ISSUE THREAD

**Issue by joshbear** [neurosutton/connectivity#2]
From fmri_analysis_functions_pd.py : when trying to run plot_score_by_network() receive the following error: 

/scripts/connectivity/fmri_analysis_functions_pd.py in plot_score_by_network(subjects_file, measure, mdata, network, drop)
    680 def plot_score_by_network(subjects_file, measure, mdata, network, drop=[]):
    681     score_df = get_subj_df_data(subjects_file)
--> 682     col = [col for col in score_df.columns if measure in col]
    683     if len(col) > 1:
    684         print(f'Found multiple matching columns for {measure}')

AttributeError: 'tuple' object has no attribute 'columns'

Looks like get_subj_df_data() is currently returning a series of 3 dictionaries — Not sure if this was changed previously or what other functions access it at this point?

**Comment by neurosutton** [comment]
I think the issue was that get_subj_df_data returned more than just the df. I've updated the code so that it should unpack the results, rather than create a tuple. Please let me know if you are still receiving the error.
