### ISSUE TITLE
Check functionality of the AUC calculation / iterative statistics. 

### ISSUE THREAD

**Issue by joshbear** [neurosutton/connectivity#9]
With the changes to the save_long_format code output, need to test the AUC calculations and statistical analysis. 
1 - Does it work with the current format?
2 - Can it accept specified subgraph / network rather than whole brain?

**Comment by neurosutton** [comment]
Ran ipynb to check the updates. (see Teams)
1 - Yes, the flexible solve for the measures in the df.columns identifies the scores that need to be permuted. Columns where scores do not exist for a network are not permuted.
2 - Yes, networks can be specified as input and the algorithm locates the network-affiliated rows right off the bat.

Note: graph_analysis_functions was changed in this commit to include a threshold for the subgraph results. Without the threshold the AUC cannot run.
